### ISSUE TITLE
Loading more dependencies

### ISSUE THREAD

**Issue by varghesep** [fadihania/angular1-typescript-systemjs#1]
Thanks for this example.
1. Is there a reason you used _systemjs_ to load modules compared to commonjs or amd? Is the reason you don't have to use _browserify_ or _webpack_ to bundle the module?
2. Is there an advantage in loading the modules using _systemjs_ compared to bundling the js files and load at once?
3. Is this approach suitable for production environment?
4. I followed your example, but have a problem loading a dependencies for the **app** module. How can I tell the system that there are two other dependencies like _dependency1_ and _dependency2_ need to be loaded? 

``` javascript
angular
    .module('app', [ 'dependency1', 'dependency2'])
    .controller('MainController', MainController);
```

**Comment by fadihania** [comment]
I was playing with Angular 2.0 "5 Min Quickstart" and I thought why not using it for Angular 1.*. So, I created this example that uses SystemJS/TypeScript and shared it.
Usually, this approach is used for development environment not for production. You'll need to minify and bundle your js files for better performance. You can find more details in [SystemJS](https://github.com/systemjs/builder).
You can update package.json and config.js to add support for your dependencies.
